-- MySQL Database Setup for Elite Hotels
-- Run this script in phpMyAdmin or MySQL command line

-- Create database
CREATE DATABASE IF NOT EXISTS elite_hotels CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Use the database
USE elite_hotels;

-- Create cities table
CREATE TABLE IF NOT EXISTS cities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    country VARCHAR(255) NOT NULL,
    description TEXT,
    image_seed VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create hotels table
CREATE TABLE IF NOT EXISTS hotels (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city_id INT NOT NULL,
    city_name VARCHAR(255) NOT NULL,
    rating INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    description TEXT,
    amenities TEXT,
    featured TINYINT(1) DEFAULT 0,
    image_seed VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE CASCADE,
    INDEX idx_city_id (city_id),
    INDEX idx_city_name (city_name),
    INDEX idx_featured (featured),
    INDEX idx_rating (rating),
    INDEX idx_price (price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create gallery_images table
CREATE TABLE IF NOT EXISTS gallery_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    image_seed VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create videos table
CREATE TABLE IF NOT EXISTS videos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100) NOT NULL,
    video_url VARCHAR(500) NOT NULL,
    thumbnail_seed VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert sample cities data
INSERT INTO cities (name, country, description, image_seed) VALUES
('Abidjan', 'Ivory Coast', 'Economic capital of Ivory Coast with modern hotels and business facilities.', 'city_abidjan'),
('Abu Dhabi', 'UAE', 'Capital of the UAE featuring luxury resorts and cultural attractions.', 'city_abudhabi'),
('Accra', 'Ghana', 'Vibrant capital city with rich culture and growing hospitality sector.', 'city_accra'),
('Addis Ababa', 'Ethiopia', 'Diplomatic capital of Africa with unique cultural experiences.', 'city_addisababa'),
('Adelaide', 'Australia', 'Wine capital of Australia with boutique hotels and fine dining.', 'city_adelaide'),
('Algiers', 'Algeria', 'Historic Mediterranean city with colonial architecture and seaside hotels.', 'city_algiers'),
('Amman', 'Jordan', 'Ancient city blending history with modern luxury accommodations.', 'city_amman'),
('Amsterdam', 'Netherlands', 'Canal city famous for its historic charm and boutique hotels.', 'city_amsterdam'),
('Ankara', 'Turkey', 'Capital city offering business hotels and cultural attractions.', 'city_ankara'),
('Antwerp', 'Belgium', 'Diamond capital with elegant hotels and historic architecture.', 'city_antwerp'),
('Arequipa', 'Peru', 'Colonial city near volcanoes with unique mountain lodge experiences.', 'city_arequipa'),
('Athens', 'Greece', 'Cradle of civilization with luxury hotels near ancient monuments.', 'city_athens'),
('Atlanta', 'USA', 'Southern hospitality meets modern luxury in this business hub.', 'city_atlanta'),
('Auckland', 'New Zealand', 'Harbor city with stunning waterfront hotels and outdoor adventures.', 'city_auckland'),
('Austin', 'USA', 'Music capital with eclectic boutique hotels and vibrant nightlife.', 'city_austin'),
('Baghdad', 'Iraq', 'Historic city with traditional hospitality and cultural heritage.', 'city_baghdad'),
('Baltimore', 'USA', 'Harbor city with historic charm and waterfront accommodations.', 'city_baltimore'),
('Bamako', 'Mali', 'Cultural hub of West Africa with authentic local experiences.', 'city_bamako'),
('Bangalore', 'India', 'Silicon Valley of India with modern business hotels and tech culture.', 'city_bangalore'),
('Bangkok', 'Thailand', 'Vibrant metropolis with luxury hotels, temples, and street food.', 'city_bangkok'),
('Bangui', 'Central African Republic', 'River city with unique cultural experiences and local hospitality.', 'city_bangui'),
('Barcelona', 'Spain', 'Architectural marvel with boutique hotels and Mediterranean charm.', 'city_barcelona'),
('Barranquilla', 'Colombia', 'Caribbean coast city famous for carnival and beachfront hotels.', 'city_barranquilla'),
('Basel', 'Switzerland', 'Art and culture hub with luxury hotels and Rhine River views.', 'city_basel'),
('Beijing', 'China', 'Ancient capital with imperial palaces and world-class hotels.', 'city_beijing'),
('Beirut', 'Lebanon', 'Paris of the Middle East with sophisticated hotels and nightlife.', 'city_beirut'),
('Berlin', 'Germany', 'Historic capital with cutting-edge design hotels and rich culture.', 'city_berlin'),
('Bern', 'Switzerland', 'Medieval capital with charming hotels and Alpine accessibility.', 'city_bern'),
('Bogotá', 'Colombia', 'High-altitude capital with colonial charm and modern luxury hotels.', 'city_bogota'),
('Bordeaux', 'France', 'Wine capital with elegant châteaux hotels and vineyard experiences.', 'city_bordeaux'),
('Boston', 'USA', 'Historic city with luxury hotels near Freedom Trail and universities.', 'city_boston'),
('Brazzaville', 'Republic of Congo', 'Congo River city with unique African hospitality experiences.', 'city_brazzaville'),
('Brisbane', 'Australia', 'Subtropical city with riverside hotels and outdoor lifestyle.', 'city_brisbane'),
('Brussels', 'Belgium', 'European capital with grand hotels and world-class dining.', 'city_brussels'),
('Bucharest', 'Romania', 'Paris of the East with elegant hotels and rich architectural heritage.', 'city_bucharest'),
('Budapest', 'Hungary', 'Danube pearl with thermal spa hotels and stunning architecture.', 'city_budapest'),
('Buenos Aires', 'Argentina', 'Tango capital with boutique hotels and European elegance.', 'city_buenosaires'),
('Busan', 'South Korea', 'Coastal city with beachfront resorts and modern amenities.', 'city_busan'),
('Cairo', 'Egypt', 'Ancient city with luxury hotels near pyramids and Nile River.', 'city_cairo'),
('Calgary', 'Canada', 'Gateway to the Rockies with mountain-view hotels and western charm.', 'city_calgary'),
('Cali', 'Colombia', 'Salsa capital with vibrant hotels and tropical atmosphere.', 'city_cali'),
('Cancun', 'Mexico', 'Beach paradise with all-inclusive resorts and Mayan culture.', 'city_cancun'),
('Cape Town', 'South Africa', 'Mother City with luxury hotels and stunning mountain views.', 'city_capetown'),
('Caracas', 'Venezuela', 'Mountain valley capital with unique urban hotel experiences.', 'city_caracas'),
('Cartagena', 'Colombia', 'Colonial jewel with boutique hotels in historic walled city.', 'city_cartagena'),
('Casablanca', 'Morocco', 'Economic hub with modern hotels and Atlantic Ocean views.', 'city_casablanca'),
('Chennai', 'India', 'Gateway to South India with business hotels and cultural attractions.', 'city_chennai'),
('Chicago', 'USA', 'Windy City with luxury hotels and world-class architecture.', 'city_chicago'),
('Chiclayo', 'Peru', 'Archaeological gateway with hotels near ancient Moche sites.', 'city_chiclayo'),
('Chisinau', 'Moldova', 'Wine country capital with boutique hotels and cellar tours.', 'city_chisinau'),
('Christchurch', 'New Zealand', 'Garden city with eco-friendly hotels and Canterbury Plains access.', 'city_christchurch'),
('Cleveland', 'USA', 'Lake Erie city with revitalized downtown hotels and cultural scene.', 'city_cleveland'),
('Cologne', 'Germany', 'Cathedral city with historic hotels and Rhine River charm.', 'city_cologne'),
('Colombo', 'Sri Lanka', 'Indian Ocean gateway with colonial hotels and tropical luxury.', 'city_colombo'),
('Copenhagen', 'Denmark', 'Design capital with minimalist luxury hotels and hygge culture.', 'city_copenhagen'),
('Cuenca', 'Ecuador', 'UNESCO World Heritage city with colonial charm and mountain hotels.', 'city_cuenca'),
('Cusco', 'Peru', 'Gateway to Machu Picchu with historic hotels in ancient Inca capital.', 'city_cusco'),
('Daegu', 'South Korea', 'Textile city with modern hotels and traditional Korean culture.', 'city_daegu'),
('Dakar', 'Senegal', 'Atlantic coast capital with beachfront hotels and vibrant culture.', 'city_dakar'),
('Dallas', 'USA', 'Big D with luxury hotels and southern hospitality in urban setting.', 'city_dallas'),
('Damascus', 'Syria', 'Ancient city with traditional hotels and historic significance.', 'city_damascus'),
('Delhi', 'India', 'Capital territory with luxury hotels blending Mughal and modern architecture.', 'city_delhi'),
('Denver', 'USA', 'Mile High City with mountain-view hotels and outdoor adventure access.', 'city_denver'),
('Detroit', 'USA', 'Motor City with revitalized downtown hotels and industrial heritage.', 'city_detroit'),
('Dhaka', 'Bangladesh', 'Bustling capital with business hotels and rich Bengali culture.', 'city_dhaka'),
('Doha', 'Qatar', 'Futuristic city with ultra-luxury hotels and desert experiences.', 'city_doha'),
('Dubai', 'UAE', 'Luxury destination with world-class resorts and architectural marvels.', 'city_dubai'),
('Dublin', 'Ireland', 'Friendly capital with charming hotels and rich literary heritage.', 'city_dublin'),
('Edinburgh', 'Scotland', 'Festival city with castle-view hotels and Scottish Highland access.', 'city_edinburgh'),
('Erbil', 'Iraq', 'Kurdish capital with modern hotels and ancient citadel views.', 'city_erbil'),
('Florence', 'Italy', 'Renaissance jewel with palazzo hotels and world-class art.', 'city_florence'),
('Frankfurt', 'Germany', 'Financial hub with business hotels and easy European access.', 'city_frankfurt'),
('Fukuoka', 'Japan', 'Kyushu gateway with modern hotels and famous ramen culture.', 'city_fukuoka'),
('Geneva', 'Switzerland', 'International city with luxury lake-view hotels and Alpine proximity.', 'city_geneva'),
('Ghent', 'Belgium', 'Medieval gem with boutique hotels and canal-side dining.', 'city_ghent'),
('Graz', 'Austria', 'UNESCO city with design hotels and Styrian wine country access.', 'city_graz'),
('Guadalajara', 'Mexico', 'Mariachi birthplace with colonial hotels and tequila experiences.', 'city_guadalajara'),
('Guangzhou', 'China', 'Pearl River city with modern hotels and Cantonese cuisine.', 'city_guangzhou'),
('Guayaquil', 'Ecuador', 'Pacific port with riverfront hotels and Galápagos gateway access.', 'city_guayaquil'),
('Gwangju', 'South Korea', 'Cultural city with traditional hotels and democratic history.', 'city_gwangju'),
('Haifa', 'Israel', 'Port city with Baháí Gardens views and Mediterranean hotels.', 'city_haifa'),
('Hamburg', 'Germany', 'Hanseatic city with harbor-view hotels and maritime culture.', 'city_hamburg'),
('Hanoi', 'Vietnam', 'Ancient capital with French colonial hotels and street food culture.', 'city_hanoi'),
('Helsinki', 'Finland', 'Nordic design capital with waterfront hotels and sauna culture.', 'city_helsinki'),
('Hiroshima', 'Japan', 'Peace memorial city with modern hotels and island shrine access.', 'city_hiroshima'),
('Ho Chi Minh City', 'Vietnam', 'Dynamic metropolis with luxury hotels and Mekong Delta access.', 'city_hcmc'),
('Hong Kong', 'China', 'Vertical city with sky-high luxury hotels and harbor views.', 'city_hongkong'),
('Houston', 'USA', 'Space City with luxury hotels and diverse culinary scene.', 'city_houston'),
('Incheon', 'South Korea', 'International gateway with airport hotels and island attractions.', 'city_incheon'),
('Innsbruck', 'Austria', 'Alpine capital with mountain hotels and Olympic heritage.', 'city_innsbruck'),
('Istanbul', 'Turkey', 'Bridge between continents with historic hotels and Bosphorus views.', 'city_istanbul'),
('Jakarta', 'Indonesia', 'Archipelago capital with luxury hotels and Indonesian culture.', 'city_jakarta'),
('Jeddah', 'Saudi Arabia', 'Red Sea gateway with modern hotels and Islamic heritage.', 'city_jeddah'),
('Jerusalem', 'Israel', 'Holy city with historic hotels and religious significance.', 'city_jerusalem'),
('Johannesburg', 'South Africa', 'Gold rush city with luxury hotels and safari access.', 'city_johannesburg'),
('Kabul', 'Afghanistan', 'Historic capital with traditional hospitality and mountain views.', 'city_kabul'),
('Kiev', 'Ukraine', 'Golden-domed capital with elegant hotels and Slavic culture.', 'city_kiev'),
('Kinshasa', 'Democratic Republic of Congo', 'Congo River metropolis with unique African experiences.', 'city_kinshasa'),
('Kolkata', 'India', 'Cultural capital with colonial hotels and intellectual heritage.', 'city_kolkata'),
('Kuala Lumpur', 'Malaysia', 'Twin Towers city with luxury hotels and multicultural cuisine.', 'city_kualalumpur'),
('Kuwait City', 'Kuwait', 'Gulf capital with modern hotels and traditional souks.', 'city_kuwaitcity'),
('Kyoto', 'Japan', 'Ancient capital with traditional ryokans and temple gardens.', 'city_kyoto'),
('La Paz', 'Bolivia', 'Highest capital with unique altitude hotels and Andean culture.', 'city_lapaz'),
('Lagos', 'Nigeria', 'Economic powerhouse with business hotels and Afrobeat culture.', 'city_lagos'),
('Las Vegas', 'USA', 'Entertainment capital with themed resort hotels and world-class shows.', 'city_lasvegas'),
('Lima', 'Peru', 'Culinary capital with luxury hotels and Pacific Ocean views.', 'city_lima'),
('Lisbon', 'Portugal', 'Hilltop capital with boutique hotels and Fado music culture.', 'city_lisbon'),
('London', 'UK', 'Royal capital with luxury hotels and rich historical heritage.', 'city_london'),
('Los Angeles', 'USA', 'City of Angels with Hollywood glamour hotels and beach access.', 'city_losangeles'),
('Luxembourg City', 'Luxembourg', 'European financial center with luxury hotels and castle views.', 'city_luxembourg'),
('Lyon', 'France', 'Gastronomic capital with boutique hotels and silk district charm.', 'city_lyon'),
('Madrid', 'Spain', 'Royal capital with grand hotels and world-class museums.', 'city_madrid'),
('Manama', 'Bahrain', 'Gulf pearl with luxury hotels and Formula 1 excitement.', 'city_manama'),
('Manchester', 'UK', 'Industrial heritage city with modern hotels and football culture.', 'city_manchester'),
('Manila', 'Philippines', 'Island capital with bay-view hotels and Spanish colonial history.', 'city_manila'),
('Marrakech', 'Morocco', 'Red city with riad hotels and Atlas Mountains proximity.', 'city_marrakech'),
('Marseille', 'France', 'Mediterranean port with coastal hotels and Provençal culture.', 'city_marseille'),
('Medellín', 'Colombia', 'City of eternal spring with innovative hotels and transformation story.', 'city_medellin'),
('Melbourne', 'Australia', 'Cultural capital with laneway hotels and coffee culture.', 'city_melbourne'),
('Memphis', 'USA', 'Blues birthplace with music-themed hotels and Mississippi River views.', 'city_memphis'),
('Mexico City', 'Mexico', 'Aztec capital with historic hotels and world-class cuisine.', 'city_mexicocity'),
('Miami', 'USA', 'Art Deco paradise with beachfront hotels and Latin flavor.', 'city_miami'),
('Milan', 'Italy', 'Fashion capital with design hotels and luxury shopping.', 'city_milan'),
('Milwaukee', 'USA', 'Brew city with lakefront hotels and German heritage.', 'city_milwaukee'),
('Minneapolis', 'USA', 'Twin Cities hub with skyway-connected hotels and lakes access.', 'city_minneapolis'),
('Minsk', 'Belarus', 'Soviet heritage city with traditional hotels and cultural experiences.', 'city_minsk'),
('Monterrey', 'Mexico', 'Mountain metropolis with business hotels and Sierra Madre views.', 'city_monterrey'),
('Montevideo', 'Uruguay', 'River Plate capital with coastal hotels and tango culture.', 'city_montevideo'),
('Montreal', 'Canada', 'French-Canadian city with boutique hotels and festival culture.', 'city_montreal'),
('Mumbai', 'India', 'Bollywood capital with luxury hotels and Arabian Sea views.', 'city_mumbai'),
('Munich', 'Germany', 'Bavarian capital with beer garden hotels and Oktoberfest tradition.', 'city_munich'),
('Muscat', 'Oman', 'Sultanate capital with luxury desert hotels and frankincense heritage.', 'city_muscat'),
('N\'Djamena', 'Chad', 'Sahel capital with unique Saharan hotel experiences.', 'city_ndjamena'),
('Nairobi', 'Kenya', 'Safari capital with wildlife-view hotels and Maasai culture.', 'city_nairobi'),
('Naples', 'Italy', 'Pizza birthplace with historic hotels and Vesuvius views.', 'city_naples'),
('Nashville', 'USA', 'Music City with honky-tonk hotels and country music heritage.', 'city_nashville'),
('New Orleans', 'USA', 'Jazz birthplace with French Quarter hotels and Creole culture.', 'city_neworleans'),
('New York', 'USA', 'The Big Apple with iconic luxury hotels and Broadway shows.', 'city_newyork'),
('Niamey', 'Niger', 'Niger River capital with Sahel culture and traditional hospitality.', 'city_niamey'),
('Nice', 'France', 'French Riviera jewel with Mediterranean luxury hotels and azure coast.', 'city_nice'),
('Nuku\'alofa', 'Tonga', 'Pacific kingdom capital with island resort hotels and Polynesian culture.', 'city_nukualofa'),
('Osaka', 'Japan', 'Kitchen of Japan with modern hotels and street food culture.', 'city_osaka'),
('Oslo', 'Norway', 'Fjord capital with design hotels and midnight sun experiences.', 'city_oslo'),
('Ottawa', 'Canada', 'Capital city with parliamentary hotels and four-season beauty.', 'city_ottawa'),
('Ouagadougou', 'Burkina Faso', 'Sahel capital with traditional hotels and West African culture.', 'city_ouagadougou'),
('Paris', 'France', 'City of Light with luxury hotels and romantic Seine River views.', 'city_paris'),
('Perth', 'Australia', 'Isolated jewel with Indian Ocean hotels and unique wildlife.', 'city_perth'),
('Philadelphia', 'USA', 'Birthplace of America with historic hotels and Liberty Bell proximity.', 'city_philadelphia'),
('Phnom Penh', 'Cambodia', 'Mekong capital with colonial hotels and Khmer culture.', 'city_phnompenh'),
('Phoenix', 'USA', 'Desert metropolis with resort hotels and Sonoran Desert access.', 'city_phoenix'),
('Pittsburgh', 'USA', 'Steel city with riverfront hotels and industrial heritage transformation.', 'city_pittsburgh'),
('Port Moresby', 'Papua New Guinea', 'Pacific capital with unique Melanesian culture and coral reef access.', 'city_portmoresby'),
('Portland', 'USA', 'Quirky city with boutique hotels and Pacific Northwest culture.', 'city_portland'),
('Prague', 'Czech Republic', 'Golden city with castle-view hotels and medieval charm.', 'city_prague'),
('Quito', 'Ecuador', 'Equatorial capital with colonial hotels and volcano views.', 'city_quito'),
('Reykjavik', 'Iceland', 'Nordic capital with geothermal hotels and Northern Lights access.', 'city_reykjavik'),
('Riga', 'Latvia', 'Baltic jewel with Art Nouveau hotels and medieval old town.', 'city_riga'),
('Rio de Janeiro', 'Brazil', 'Marvelous city with beachfront hotels and Christ the Redeemer views.', 'city_rio'),
('Riyadh', 'Saudi Arabia', 'Desert capital with luxury hotels and modern Arabian architecture.', 'city_riyadh'),
('Rome', 'Italy', 'Eternal city with historic hotels and ancient Roman monuments.', 'city_rome'),
('Rotterdam', 'Netherlands', 'Modern port city with architectural hotels and innovative design.', 'city_rotterdam'),
('Salzburg', 'Austria', 'Mozart\'s birthplace with baroque hotels and Sound of Music locations.', 'city_salzburg'),
('San Antonio', 'USA', 'Alamo city with River Walk hotels and Tex-Mex culture.', 'city_sanantonio'),
('San Francisco', 'USA', 'Golden Gate city with boutique hotels and cable car charm.', 'city_sanfrancisco'),
('Santiago', 'Chile', 'Andean capital with mountain-view hotels and wine country access.', 'city_santiago'),
('São Paulo', 'Brazil', 'Megacity with business hotels and vibrant cultural scene.', 'city_saopaulo'),
('Sapporo', 'Japan', 'Snow festival city with winter resort hotels and beer culture.', 'city_sapporo'),
('Seattle', 'USA', 'Emerald city with waterfront hotels and coffee culture.', 'city_seattle'),
('Seoul', 'South Korea', 'K-pop capital with high-tech hotels and traditional palaces.', 'city_seoul'),
('Shanghai', 'China', 'Pearl of the Orient with luxury hotels and Bund waterfront views.', 'city_shanghai'),
('Shenzhen', 'China', 'Tech hub with modern hotels and Hong Kong border proximity.', 'city_shenzhen'),
('Singapore', 'Singapore', 'Garden city with luxury hotels and multicultural cuisine.', 'city_singapore'),
('Skopje', 'North Macedonia', 'Balkan capital with historic hotels and Ottoman heritage.', 'city_skopje'),
('Sofia', 'Bulgaria', 'Rose valley capital with mountain hotels and Orthodox culture.', 'city_sofia'),
('Stockholm', 'Sweden', 'Venice of the North with archipelago hotels and Nobel heritage.', 'city_stockholm'),
('Stuttgart', 'Germany', 'Mercedes city with automotive hotels and Swabian culture.', 'city_stuttgart'),
('Suva', 'Fiji', 'Pacific paradise capital with tropical resort hotels and coral reefs.', 'city_suva'),
('Sydney', 'Australia', 'Harbor city with Opera House view hotels and beach culture.', 'city_sydney'),
('Taipei', 'Taiwan', 'Formosa capital with night market hotels and bubble tea culture.', 'city_taipei'),
('Tallinn', 'Estonia', 'Medieval Baltic capital with old town hotels and digital innovation.', 'city_tallinn'),
('Tashkent', 'Uzbekistan', 'Silk Road capital with traditional hotels and Islamic architecture.', 'city_tashkent'),
('Tehran', 'Iran', 'Persian capital with mountain hotels and rich cultural heritage.', 'city_tehran'),
('Tel Aviv', 'Israel', 'Mediterranean tech hub with beachfront hotels and startup culture.', 'city_telaviv'),
('The Hague', 'Netherlands', 'International justice city with diplomatic hotels and North Sea access.', 'city_thehague'),
('Tijuana', 'Mexico', 'Border city with modern hotels and Baja California wine access.', 'city_tijuana'),
('Tokyo', 'Japan', 'Neon metropolis with luxury hotels and traditional culture blend.', 'city_tokyo'),
('Toronto', 'Canada', 'Multicultural hub with CN Tower view hotels and diverse neighborhoods.', 'city_toronto'),
('Toulouse', 'France', 'Pink city with aerospace hotels and Occitan culture.', 'city_toulouse'),
('Trujillo', 'Peru', 'Colonial city with archaeological hotels and Moche pyramid access.', 'city_trujillo'),
('Tunis', 'Tunisia', 'Carthage capital with medina hotels and Mediterranean culture.', 'city_tunis'),
('Ulsan', 'South Korea', 'Industrial city with coastal hotels and whale watching opportunities.', 'city_ulsan'),
('Vancouver', 'Canada', 'Mountain and ocean city with scenic hotels and outdoor adventures.', 'city_vancouver'),
('Venice', 'Italy', 'Floating city with canal-view hotels and romantic gondola rides.', 'city_venice'),
('Vienna', 'Austria', 'Imperial capital with palace hotels and classical music heritage.', 'city_vienna'),
('Vilnius', 'Lithuania', 'Baroque Baltic capital with old town hotels and amber culture.', 'city_vilnius'),
('Warsaw', 'Poland', 'Phoenix city with modern hotels and reconstructed historic center.', 'city_warsaw'),
('Washington DC', 'USA', 'Capital city with monument-view hotels and Smithsonian access.', 'city_washingtondc'),
('Wellington', 'New Zealand', 'Windy capital with harbor hotels and Lord of the Rings locations.', 'city_wellington'),
('Yangon', 'Myanmar', 'Golden pagoda city with colonial hotels and Buddhist culture.', 'city_yangon'),
('Zurich', 'Switzerland', 'Financial capital with lake-view hotels and Alpine accessibility.', 'city_zurich')
ON DUPLICATE KEY UPDATE description = VALUES(description);

-- Insert sample hotels data (you can add more as needed)
INSERT INTO hotels (name, city_id, city_name, rating, price, description, amenities, featured, image_seed) VALUES
-- Abidjan Hotels
(1, 'Grand Hotel Abidjan', 1, 'Abidjan', 5, 180.00, 'Luxury business hotel in the heart of Abidjan with modern amenities and excellent service.', 'WiFi, Pool, Spa, Restaurant, Business Center, Gym', 1, 'hotel_abidjan_1'),
(2, 'Plateau Business Hotel', 1, 'Abidjan', 4, 120.00, 'Modern hotel in the business district with comfortable rooms and conference facilities.', 'WiFi, Restaurant, Business Center, Gym, Parking', 0, 'hotel_abidjan_2'),
(3, 'Cocody Resort', 1, 'Abidjan', 4, 150.00, 'Peaceful resort-style hotel with tropical gardens and relaxing atmosphere.', 'WiFi, Pool, Restaurant, Garden, Spa', 0, 'hotel_abidjan_3'),

-- Abu Dhabi Hotels  
(4, 'Emirates Palace Abu Dhabi', 2, 'Abu Dhabi', 5, 450.00, 'Iconic luxury palace hotel with gold-plated interiors and world-class amenities.', 'WiFi, Pool, Spa, Restaurant, Beach Access, Butler Service', 1, 'hotel_abudhabi_1'),
(5, 'Corniche Grand Hotel', 2, 'Abu Dhabi', 4, 280.00, 'Waterfront hotel with stunning views of the Arabian Gulf and modern facilities.', 'WiFi, Pool, Restaurant, Beach Access, Gym', 0, 'hotel_abudhabi_2'),
(6, 'Desert Oasis Resort', 2, 'Abu Dhabi', 4, 320.00, 'Unique desert experience with luxury tents and traditional Arabian hospitality.', 'WiFi, Pool, Spa, Restaurant, Desert Safari, Camel Rides', 0, 'hotel_abudhabi_3'),

-- New York Hotels
(7, 'Manhattan Grand Hotel', 138, 'New York', 5, 350.00, 'Iconic luxury hotel in the heart of Manhattan with Central Park views.', 'WiFi, Spa, Restaurant, Concierge, Business Center, Gym', 1, 'hotel_newyork_1'),
(8, 'Brooklyn Bridge Suites', 138, 'New York', 4, 250.00, 'Modern hotel with stunning bridge views and contemporary amenities.', 'WiFi, Restaurant, Gym, Business Center, Rooftop Bar', 0, 'hotel_newyork_2'),
(9, 'Times Square Plaza', 138, 'New York', 4, 280.00, 'Vibrant hotel in the heart of Times Square with Broadway show access.', 'WiFi, Restaurant, Theater Tickets, Concierge, Gym', 0, 'hotel_newyork_3'),

-- London Hotels
(10, 'Royal Westminster Hotel', 108, 'London', 5, 400.00, 'Historic luxury hotel near Westminster Abbey with traditional British elegance.', 'WiFi, Spa, Restaurant, Afternoon Tea, Concierge, Business Center', 1, 'hotel_london_1'),
(11, 'Thames View Suites', 108, 'London', 4, 300.00, 'Modern hotel with panoramic Thames River views and contemporary design.', 'WiFi, Restaurant, River Views, Gym, Business Center', 0, 'hotel_london_2'),
(12, 'Covent Garden Boutique', 108, 'London', 4, 280.00, 'Charming boutique hotel in the cultural heart of London.', 'WiFi, Restaurant, Theater District, Concierge, Gym', 0, 'hotel_london_3'),

-- Paris Hotels
(13, 'Le Grand Palais Paris', 146, 'Paris', 5, 380.00, 'Elegant hotel near the Louvre with classic French luxury and sophistication.', 'WiFi, Spa, Restaurant, Concierge, Business Center, Gym', 1, 'hotel_paris_1'),
(14, 'Montmartre Artist Hotel', 146, 'Paris', 4, 220.00, 'Charming hotel in the artistic Montmartre district with bohemian atmosphere.', 'WiFi, Restaurant, Art Gallery, Concierge, Gym', 0, 'hotel_paris_2'),
(15, 'Champs-Élysées Luxury', 146, 'Paris', 4, 320.00, 'Sophisticated hotel on the famous avenue with shopping and dining access.', 'WiFi, Restaurant, Shopping Access, Concierge, Spa', 0, 'hotel_paris_3'),

-- Tokyo Hotels
(16, 'Imperial Tokyo Hotel', 186, 'Tokyo', 5, 420.00, 'Traditional luxury hotel blending Japanese hospitality with modern amenities.', 'WiFi, Spa, Restaurant, Tea Ceremony, Business Center, Gym', 1, 'hotel_tokyo_1'),
(17, 'Shibuya Modern Suites', 186, 'Tokyo', 4, 280.00, 'Contemporary hotel in the bustling Shibuya district with city views.', 'WiFi, Restaurant, City Views, Gym, Business Center', 0, 'hotel_tokyo_2'),
(18, 'Ginza Boutique Hotel', 186, 'Tokyo', 4, 350.00, 'Upscale hotel in the luxury shopping district with refined Japanese design.', 'WiFi, Restaurant, Shopping Access, Spa, Concierge', 0, 'hotel_tokyo_3'),

-- Sydney Hotels
(19, 'Harbour Bridge Grand', 178, 'Sydney', 5, 380.00, 'Iconic hotel with stunning harbour views and Opera House proximity.', 'WiFi, Pool, Restaurant, Harbour Views, Spa, Concierge', 1, 'hotel_sydney_1'),
(20, 'Bondi Beach Resort', 178, 'Sydney', 4, 250.00, 'Beachfront hotel with direct beach access and surf culture immersion.', 'WiFi, Pool, Restaurant, Beach Access, Surf Lessons, Gym', 0, 'hotel_sydney_2'),
(21, 'Darling Harbour Suites', 178, 'Sydney', 4, 300.00, 'Modern hotel in the entertainment district with waterfront dining.', 'WiFi, Restaurant, Entertainment Access, Gym, Business Center', 0, 'hotel_sydney_3')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- Insert sample gallery images
INSERT INTO gallery_images (title, category, image_seed, description) VALUES
('Luxury Hotel Exterior', 'exterior', 'gallery_exterior_1', 'Stunning architectural design of our flagship hotel'),
('Presidential Suite', 'rooms', 'gallery_room_1', 'Spacious presidential suite with panoramic city views'),
('Infinity Pool', 'amenities', 'gallery_pool_1', 'Rooftop infinity pool overlooking the city skyline'),
('Fine Dining Restaurant', 'dining', 'gallery_dining_1', 'Award-winning restaurant with world-class cuisine'),
('Spa Treatment Room', 'amenities', 'gallery_spa_1', 'Tranquil spa environment for ultimate relaxation'),
('Grand Lobby', 'interior', 'gallery_lobby_1', 'Elegant lobby with marble floors and crystal chandeliers'),
('Business Conference Room', 'business', 'gallery_conference_1', 'State-of-the-art conference facilities for corporate events'),
('Hotel Garden Terrace', 'exterior', 'gallery_garden_1', 'Beautiful landscaped gardens and outdoor seating areas')
ON DUPLICATE KEY UPDATE title = VALUES(title);